### ISSUE TITLE
Replicate a version of plot_degree.gif in d3 using r2d3

### ISSUE THREAD

**Issue by jhofman** [jhofman/datamations#10]
Create a version of the full animation [here](https://osf.io/n86cf/) for `small_salary` data of 100 points in d3 using r2d3.

This should load the data:

```
load('src/dmpkg/data/small_salary_100.rda')
```

For now, let's go for the following key frames:

1. Ungrouped data, in a grid all grey.
2. Grouped data, in a grid blue and red.
3. Scatter plot (x = degree, y = salary, color = degree), as you have from #5.
4. Collapsed points for averages (x = degree, y = average_salary, color = degree), also from #5.

There will be issues with scales zooming in and with showing error bars, etc., that we can address in a future iteration.

**Comment by giorgi-ghviniashvili** [comment]
Hi @jhofman. 

Here is the video:
https://user-images.githubusercontent.com/6615532/113862991-27a88980-97ba-11eb-9ad3-b8725506e63d.mov

I separated coordinate calculation and drawing logic into their own functions. The calculation and drawing initialization happens in `main()`. 

```javascript
  const frames = [];
  frames.push(grid());
  frames.push(colored_grid());
  frames.push(scatter_plot());
  frames.push(averages());
```

Frames are scenically animated.

**Comment by jhofman** [comment]
@giorgi-ghviniashvili, quick question on the scatter portion of this ("step 3"), do the y coordinates correspond to actual salary amounts? 

if not, can you update things so that's the case?

**Comment by giorgi-ghviniashvili** [comment]
@jhofman  yes they use salary amounts, but then collision detection is applied which spreads the nodes a bit.

**Comment by giorgi-ghviniashvili** [comment]
If I set exact y coords, I am getting this: 
![image](https://user-images.githubusercontent.com/6615532/113871280-ca193a80-97c3-11eb-96d1-c9042b27f2d1.png)

**Comment by jhofman** [comment]
ah okay. is there a way to keep the y coords exact but jitter on the x coords only to avoid collisions?

**Comment by giorgi-ghviniashvili** [comment]
Ok, done it: 
![image](https://user-images.githubusercontent.com/6615532/113874408-d2bf4000-97c6-11eb-9a7d-d5cc57d9db4e.png)
