### ISSUE TITLE
Step through README examples and comment code to clarify

### ISSUE THREAD

**Issue by jhofman** [jhofman/datamations#11]
Presumably there's a lot of coordinate hacking to get animations to line up. Would be good to know how much of this is happening and where.

**Comment by sharlagelfand** [comment]
I've put a bunch of comments in the `examples-step` branch, especially looking at the different stages in the summarise animation step.

Here are some super rough notes, but a bit more concrete looking frame by frame - we can review next call and I'll explain :)
<img width="1965" alt="Screen Shot 2021-04-07 at 5 03 34 PM" src="https://user-images.githubusercontent.com/15895337/113933975-36476e80-97c3-11eb-953b-39e1d028ba1e.png">

**Comment by jhofman** [comment]
awesome notes, looking forward to hearing more!

**Comment by jhofman** [comment]
@sharlagelfand: just taking a pass through issues to clean things up. should we close this?

**Comment by sharlagelfand** [comment]
@jhofman good to close for me - I have my notes in a branch and am using + integrating them as I go through / refactor but I don't think any need to merge the branch specifically
