### ISSUE TITLE
Figure out where d3.js files can go in current repo

### ISSUE THREAD

**Issue by jhofman** [jhofman/datamations#2]
Make sure this is a spot that doesn't create conflicts with the current R package structure.

**Comment by jhofman** [comment]
@sharlagelfand: can you suggest a directory that @giorgi-ghviniashvili can use to put d3 experiments (.js files and corresponding .R or .Rmd files that call them)?

I'd like to make sure this doesn't conflict with the structure of the R package.

**Comment by sharlagelfand** [comment]
@jhofman @giorgi-ghviniashvili Maybe somewhere like a `sandbox/` subdirectory in the main directory? If we add the subdirectory to the `.Rbuildignore` file then it won't be picked up by the package development process. 

Would involve adding a line like this:

`^sandbox$`

to the `.Rbuildignore` file

**Comment by jhofman** [comment]
@sharlagelfand this seems reasonable to me. 

@giorgi-ghviniashvili, can you try this strategy in a branch when you work on #10?

**Comment by jhofman** [comment]
Sounds like `sandbox/` is a good place to put exploratory / throw-away scripts. 

When we get to the point that we have `.js` files we'd like to be part of the package, we can put those in `inst/` as per this: https://r-pkgs.org/inst.html

**Comment by giorgi-ghviniashvili** [comment]
Reasonable for me as well. Created a branch called [gio/d3](https://github.com/jhofman/datamations/tree/gio/d3), added sandbox directory and `^sandbox$` to .Rbuildignore.
