### ISSUE TITLE
Figure out how to view vega/gemini renderings in R browser

### ISSUE THREAD

**Issue by jhofman** [jhofman/datamations#22]
At some point we need to load the appropriate javascript libraries and pass data from R to html.

Can do so with files, but is there a better way (akin to r2d3)?

**Comment by sharlagelfand** [comment]
Moving the htmlwidgets discussion to here @jhofman @giorgi-ghviniashvili so it doesn't get lost in a conversation about Shiny apps. 

I overwrote the bar chart shiny app with one that takes datamations frames, but here is how it works in a static R script (with info on how to install/run the app if you want)

```r
library(dplyr)
library(palmerpenguins)
# Install code from branch (or just check it out)
# devtools::install_github("jhofman/datamations", ref = "vegalite-shiny")
library(datamations)

# Run app with 
datamations::run_app()

# Or just see output

mtcars %>%
  count(disp, name = "y") %>%
  rename(x = disp) %>%
  vegaliteBar()
```

![visualization (1)](https://user-images.githubusercontent.com/15895337/116111036-421ca700-a684-11eb-91d4-062e3f3e2f45.png)


```r
penguins %>%
  count(species, name = "y") %>%
  rename(x = species) %>%
  vegaliteBar()
```

![visualization (2)](https://user-images.githubusercontent.com/15895337/116111049-45b02e00-a684-11eb-9045-d71eb594ce99.png)

To explain the [htmlwidgets](https://www.htmlwidgets.org/) structure....

1. `vegaliteBar()` is an R function defined in [`R/vegaliteBar.R`](https://github.com/jhofman/datamations/blob/vegalite-shiny/R/vegaliteBar.R#L4) that takes the data as an argument and passes it immediately to the htmlwidgets framework to create a widget (named "vegaliteBar")
2. [`inst/htmlwidgets/vegaliteBar.js`](https://github.com/jhofman/datamations/blob/vegalite-shiny/inst/htmlwidgets/vegaliteBar.js) is part of this framework - it takes the data passed from `vegaliteBar()`, converts it to the correct format, calls the `barChart()` js function on that data, and then embeds it in the element. The structure of this file is all predetermined by the `htmlwidgets` framework. It is also named "vegaliteBar" which is how the R and JS functions are connected.
3. [`inst/htmlwidgets/barChart/barChart.js`](https://github.com/jhofman/datamations/blob/vegalite-shiny/inst/htmlwidgets/barChart/barChart.js) contains the `barChart()` function to actually create the vegalite bar chart from the data. This code is short enough that it could just be contained within `vegaliteBar.js`, but it'll probably be nice for us to separate out the code that creates the visualization from the code that creates the widget (above)
4. [`inst/htmlwidgets/vegaliteBar.yaml`](https://github.com/jhofman/datamations/blob/vegalite-shiny/inst/htmlwidgets/vegaliteBar.yaml) defines all of the dependencies for the widget. They are stores locally in `inst/htmlwidgets/`

When you call `vegaliteBar()`, it renders the visualization in the RStudio viewer (a browser inside RStudio). 

The ability to embed in a shiny app is just a given with the htmlwidgets structure - you create the widget with `vegaliteBar()`, [render it](https://github.com/jhofman/datamations/blob/vegalite-shiny/R/run_app.R#L28) in the server function as a "vegaliteBar" type, then put the output as a [vegaliteBar type output](https://github.com/jhofman/datamations/blob/vegalite-shiny/R/run_app.R#L13) in the UI. This idea of "render in the server" and "output in the UI" is the same for all Shiny apps, and automatically provided by the htmlwidgets framework.

Hope that is clear! Let me know if there's any questions.

**Comment by jhofman** [comment]
thanks for the great explanation of how this works @sharlagelfand!

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand I just saw that you integrated my code into the shiny app in `datamations-widget` branch. Could you please help me run that shiny app locally (without `devtools::install_github("jhofman/datamations", ref = "datamations-widget"`)?

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili I'm still working on it, it's not fully functional yet unfortunately! But good spot 😄 

This is just a widget that will be viewable in the RStudio viewer pane, not yet in any shiny app.

You can see where it is at so far though by running:

```r
devtools::load_all() # to load the latest version of the code
datamationSandDance("test") # doesn't matter what the message is since it's not used, but has to have something
```

<img width="1181" alt="Screen Shot 2021-04-27 at 1 42 31 PM" src="https://user-images.githubusercontent.com/15895337/116287948-fdb20980-a75e-11eb-88f9-6cb8a1459b34.png">


You can open it in your browser by clicking the button outlined in red.

The animating doesn't work yet, but in case it's easier for you to inspect in the browser and figure out why than it would be for me, the HTML is defined [here](https://github.com/jhofman/datamations/blob/datamations-widget/R/datamationSandDance.R#L54) (this is what gives the div where the chart actually is a random ID) and the JS is all defined [here](https://github.com/jhofman/datamations/blob/datamations-widget/inst/htmlwidgets/datamationSandDance.js#L13).

**Comment by giorgi-ghviniashvili** [comment]
Thanks! I just did not know about `devtools::load_all()`, I set working directory to `datamations` and then it worked. 
Let me try to fix that widget or at least see how it works.

**Comment by sharlagelfand** [comment]
Sounds good! If you open the `datamations.Rproj` file, in RStudio it will set the working directory to be datamations by default when you are in that project, rather than having to set it

**Comment by giorgi-ghviniashvili** [comment]
It says that `play()` function not defined. If you call play() directly after init() datamationSandDance.js it will play it.

**Comment by sharlagelfand** [comment]
Have figured out getting the `play()` button working in this widget! Updated code is in the [`datamations-widget` branch]() - note that the JS for the [widget](https://github.com/jhofman/datamations/blob/datamations-widget/inst/htmlwidgets/datamationSandDance.js) is quite small, and it mostly calls [external functions](https://github.com/jhofman/datamations/blob/datamations-widget/inst/htmlwidgets/js/datamationsFunctions.js) that do all the work. I've also updated `init()` and `play()` to take an ID so that we could have multiple widgets on a page, and the button would operate on the correct widget.

So this code produces a widget which can be played via the button:

```r
datamationSandDance()
```


https://user-images.githubusercontent.com/15895337/116419572-30194080-a80b-11eb-983a-40cc42d2e2d4.mov

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand this [PR](https://github.com/jhofman/datamations/pull/35) includes the simplified version of js, only play button. Removed slider and dataset name.

**Comment by sharlagelfand** [comment]
This widget is [in an app](https://sharlagelfand.shinyapps.io/datamations/) now, you can select which of the specs to animate. This will likely converge with #23 sooner rather than later to use @giorgi-ghviniashvili's generalized animation engine shown [here](https://rawcdn.githack.com/jhofman/datamations/gio/generalization/sandbox/app/index.html), but just an update on where the "gemini in R" bits are at!

**Comment by jhofman** [comment]
Closing this since I think the new issues cover what comes next.
