### ISSUE TITLE
Shiny app illustrating widget

### ISSUE THREAD

**Issue by sharlagelfand** [jhofman/datamations#38]
Again, once #23 is closed out and the widget is functional, should create a Shiny app that allows you to choose a data set, grouping variables, summary variable + operation, and shows the code and widget/animation, similar to [the app here](https://nshrest.shinyapps.io/datawhats/).

I had a live prototype of this that I wrote over (!) but the code is [here](https://github.com/jhofman/datamations/blob/refactor-test/R/run_app.R) for reusing.

**Comment by sharlagelfand** [comment]
No datamations in it yet but here's a [skeleton for the app](https://sharlagelfand.shinyapps.io/datamations/) - allows you to select data, grouping variables, summary variable + operation, then shows the pipeline, initial data set, transformed data, and a plot of the final data. May not want/need all these elements but just to include something for now!

cc @jhofman @dggoldst

**Comment by sharlagelfand** [comment]
I've updated the app [here](https://sharlagelfand.shinyapps.io/datamations/) to show the datamations! cc @jhofman @dggoldst @giorgi-ghviniashvili

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand awesome!
