### ISSUE TITLE
Axes and legend appearing too late

### ISSUE THREAD

**Issue by sharlagelfand** [jhofman/datamations#47]
@giorgi-ghviniashvili just wanted to track here the issue that axes are appearing too late - they should appear as soon as the infogrid -> jitter transition starts, but they appear when jitter -> summary starts:

https://user-images.githubusercontent.com/15895337/118002420-975be800-b315-11eb-9427-469130e5cd81.mov

I also just noticed that the legend doesn't appear until jitter -> summary! Ideally it should appear as soon as the faceted infogrid starts to animate into the colored version. Maybe has to do with the fake axes and when those show up?

You can see this on the [app](https://sharlagelfand.shinyapps.io/datamations/) with `dataset: penguins` and `group by: species, island, sex`

Thanks!

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand you have `axis: null` in encoding for jitter spec, could you please remove `axis: null`?

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  fixed it, please check it [here](https://raw.githack.com/jhofman/datamations/gio/generalization/sandbox/app/index.html).

**Comment by sharlagelfand** [comment]
thanks @giorgi-ghviniashvili, axes looks good! is it possible to fix the legend too?

**Comment by giorgi-ghviniashvili** [comment]
Whats wrong with the legend?

**Comment by sharlagelfand** [comment]
From my first comment :)

> I also just noticed that the legend doesn't appear until jitter -> summary! Ideally it should appear as soon as the faceted infogrid starts to animate into the colored version. Maybe has to do with the fake axes and when those show up?

**Comment by giorgi-ghviniashvili** [comment]
Ah, fixed it now. I was setting legend to null for all case, but now I am setting to null if `meta.axes`.

**Comment by sharlagelfand** [comment]
Thanks @giorgi-ghviniashvili! In the video below is the legend moving positions due to have it from fake axes vs from real axes? Not sure what causes this


https://user-images.githubusercontent.com/15895337/118134736-40ffaf80-b3d0-11eb-8260-fae6a7203934.mov

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand yes, that's because the width is changing..

**Comment by giorgi-ghviniashvili** [comment]
Fixed it! @sharlagelfand

**Comment by sharlagelfand** [comment]
looks good now @giorgi-ghviniashvili ty!!
