### ISSUE TITLE
Points moving across facets

### ISSUE THREAD

**Issue by sharlagelfand** [jhofman/datamations#48]
@giorgi-ghviniashvili I haven't been able to figure out why points are moving across facets - as far as I can tell the IDs match! Could you take a look? The example in #47 shows it and also this one in the app with `dataset: penguins` and `group by: species, island, sex`:

https://user-images.githubusercontent.com/15895337/118013158-d1ca8280-b31f-11eb-8b5f-f82f1b8042b2.mov

The specs for this case are [here](https://github.com/jhofman/datamations/tree/fixes/sandbox/specs-for-infogrid).

Thanks!!

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand found one issue: Adelie and Torgersen has 5 NA points, while jitter one has 4:

![image](https://user-images.githubusercontent.com/6615532/118019383-fcd9c400-b369-11eb-9cb4-823ee0f33b14.png)

**Comment by sharlagelfand** [comment]
@giorgi-ghviniashvili one of the Y values is actually `NA` (/null) so it shouldn't show up in the jittering - is it possible to have that point shown in the infogrid then "disappear" when move to jittering?

I have it worked out so the ID of the NA one isn't in the specs ([here](https://github.com/jhofman/datamations/blob/fixes/sandbox/specs-for-infogrid/05-jitter.json#L1178) - there is id 147 and 149, but no 148 since that value is missing), but maybe that's not how gemini actually works - thought it might pick up the ID being gone between frames and fade it out?

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand it should work like you describe, the point with id 148 should be gone in exit selection of d3, but needs a bit more exploration why it does not work like that. Will dive into it.

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand  I found the issue. The gemini's recommendations did not correctly generate the animation spec. I manually updated gem spec for third frame and got this:

https://user-images.githubusercontent.com/6615532/118154598-4d175b80-b428-11eb-86fa-0c00e9eb3297.mov

In general, I should come up with general solution.

**Comment by giorgi-ghviniashvili** [comment]
@sharlagelfand It is not a bug with the gemini, but the initialization object (my fault!). I modified it and now it correctly recommends. It was not correctly setting gemini_id.

**Comment by sharlagelfand** [comment]
thank you!!! looks good 🎉
