### ISSUE TITLE
Get a basic d3.js example working with r2d3

### ISSUE THREAD

**Issue by jhofman** [jhofman/datamations#5]
This package, [r2d3](https://github.com/rstudio/r2d3), should allow you to execute d3.js files in R.

**Comment by jhofman** [comment]
This looks like it's sandboxed in its own svg. @giorgi-ghviniashvili, is this flexible enough for what we want to do?

**Comment by jhofman** [comment]
More documentation: https://rstudio.github.io/r2d3/

**Comment by jhofman** [comment]
See if you can pass a full dataframe from R to d3 using `r2d3` and render a simple x-y scatter plot with the following data.

```
df <- data.frame(x = c(1,2,3), y = c(15,25,35), color = c('red','red','blue'))
```

If that works, try using the actual data in [data-raw](../tree/main/data-raw) to create a plot where the x axis is degree (masters or phd), the y axis is salary, and points are colored by degree. (Jitter on the x axis is optional for now.)

![Screen Shot 2021-04-05 at 2 23 29 PM](https://user-images.githubusercontent.com/79563/113610022-964ee100-961a-11eb-8fd4-3ad25f82390d.png)


Bonus would be to turn this into an animation where the first frame is this scatter plot and the last frame shows only the averages in each group, as in the final frame of the demo animation from the R package.

![Screen Shot 2021-04-05 at 2 23 35 PM](https://user-images.githubusercontent.com/79563/113610078-a961b100-961a-11eb-8f7d-eb96ee0e6f53.png)

The error bars are optional for now as well.

**Comment by jhofman** [comment]
The [R for Data Science](https://r4ds.had.co.nz/data-import.html?q=read_tsv#exercises-21) book is a good resource.

**Comment by giorgi-ghviniashvili** [comment]
Hi @jhofman .

I have done the scatterplot with csv data frame (`read_csv`).

Here is the video:

https://user-images.githubusercontent.com/6615532/113686906-d379a880-96d8-11eb-9df3-0c1d3005a16a.mov

Jitter done using `d3.forceCollide`.

Setup an interval method which just toggles between average or full view.

**Comment by jhofman** [comment]
Great.

After we resolve #2, let's get this code in a branch and then pull request if it's useful to keep it around.
